import { describe, expect, it } from 'vitest';
import { sortFileList, normalizeLineEndings, stripTimestamps } from './stability';
import { ApplyChange } from '../apply/types';

describe('stability', () => {
  it('sortFileList sorts files deterministically', () => {
    const files: ApplyChange[] = [
      { path: 'b.txt', status: 'added' },
      { path: 'a.txt', status: 'added' },
    ];
    const sorted = sortFileList(files);
    expect(sorted[0].path).toBe('a.txt');
    expect(sorted[1].path).toBe('b.txt');
  });

  it('normalizeLineEndings converts CRLF to LF', () => {
    const input = 'line1\r\nline2\r\nline3';
    expect(normalizeLineEndings(input)).toBe('line1\nline2\nline3');
  });

  it('stripTimestamps removes run ID', () => {
    const input = 'Generated by AgentOps\nRun ID: 123456789\nEnd';
    expect(stripTimestamps(input)).toBe('Generated by AgentOps\nRun ID: <stripped>\nEnd');
  });
});
